
export const types = {
    GET_BOOKS:'GET_BOOKS',
    GET_BOOKS_SUCCESS:'GET_BOOKS_SUCCESS',
    GET_BOOKS_FAILED:'GET_BOOKS_FAILED',
    GET_BOOK:'GET_BOOKS',
    GET_BOOK_SUCCESS:'GET_BOOKS_SUCCESS',
    GET_BOOK_FAILED:'GET_BOOKS_FAILED',
    RESET_STATE:'RESET_DATA'
}